---
version: "3.8"
services:

  tiktok-live-recorder:
    build:
      context: .
    volumes:
      - ./data/:/var/data/
    command: -room_id 7338689440947276550 -mode automatic -output /var/data/ -ffmpeg
    restart: unless-stopped
